#ifndef DIO_CONFIG_H
#define DIO_CONFIG_H

#include "Dio.h"
#include "gpio.h"

#define DIO_CONFIGURED_CHANNEL_COUNT DIO_CHANNEL_COUNT

/*LED0信号IO输出*/
#define DIO_CHANNEL_LED0_PORT   GPIOE
#define DIO_CHANNEL_LED0_PIN    GPIO_PIN_0
/*LED1信号IO输出*/
#define DIO_CHANNEL_LED1_PORT   GPIOE
#define DIO_CHANNEL_LED1_PIN    GPIO_PIN_1
/*PM1_CTRL_SD信号IO输出*/
#define DIO_CHANNEL_PM1_CTRL_SD_PORT   GPIOF
#define DIO_CHANNEL_PM1_CTRL_SD_PIN    GPIO_PIN_10
/*KEY0按键信号IO输入*/
#define DIO_CHANNEL_KEY0_PORT   GPIOE
#define DIO_CHANNEL_KEY0_PIN    GPIO_PIN_2
/*KEY1按键信号IO输入*/
#define DIO_CHANNEL_KEY1_PORT   GPIOE
#define DIO_CHANNEL_KEY1_PIN    GPIO_PIN_3
/*KEY2按键信号IO输入*/
#define DIO_CHANNEL_KEY2_PORT   GPIOE
#define DIO_CHANNEL_KEY2_PIN    GPIO_PIN_4



#endif /* DIO_CONFIG_H */
