/**
 * sfun_PosCtrlInit.c
 *
 *    ABSTRACT:
 *      The purpose of this sfunction is to call a simple legacy
 *      function during simulation:
 *
 *         void PosCtrlInit(PosCtrlHandle_t y1[1])
 *
 *    Simulink version           : 10.4 (R2021b) 14-May-2021
 *    C source code generated on : 13-May-2024 19:44:11
 *
 * THIS S-FUNCTION IS GENERATED BY THE LEGACY CODE TOOL AND MAY NOT WORK IF MODIFIED
 */

/**
     %%%-MATLAB_Construction_Commands_Start
     def = legacy_code('initialize');
     def.SFunctionName = 'sfun_PosCtrlInit';
     def.OutputFcnSpec = 'void PosCtrlInit(PosCtrlHandle_t y1[1])';
     def.HeaderFiles = {'trajectory_ctrl.h'};
     def.SourceFiles = {'trajectory_ctrl.c'};
     legacy_code('sfcn_cmex_generate', def);
     legacy_code('compile', def);
     %%%-MATLAB_Construction_Commands_End
 */

/* Must specify the S_FUNCTION_NAME as the name of the S-function */
#define S_FUNCTION_NAME  sfun_PosCtrlInit
#define S_FUNCTION_LEVEL 2

/**
 * Need to include simstruc.h for the definition of the SimStruct and
 * its associated macro definitions.
 */
#include "simstruc.h"

#include <string.h>
#include <stdlib.h>

/* Specific header file(s) required by the legacy code function */
#include "trajectory_ctrl.h"

#define IS_SIMULATION_TARGET(S) (ssRTWGenIsAccelerator(S) || ssIsRapidAcceleratorActive(S) || ssRTWGenIsModelReferenceSimTarget(S) || (ssGetSimMode(S)==SS_SIMMODE_NORMAL) || (ssGetSimMode(S)==SS_SIMMODE_SIZES_CALL_ONLY) || !((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) && GetRTWEnvironmentMode(S)==0))


/* Utility function prototypes */
static void CheckDataTypes(SimStruct *S);
static int_T GetRTWEnvironmentMode(SimStruct *S);

/* Function: mdlInitializeSizes ===========================================
 * Abstract:
 *   The sizes information is used by Simulink to determine the S-function
 *   block's characteristics (number of inputs, outputs, states, etc.).
 */
static void mdlInitializeSizes(SimStruct *S)
{
    /* Flag for detecting standalone or simulation target mode */
    boolean_T isSimulationTarget = IS_SIMULATION_TARGET(S);

    /* Number of expected parameters */
    ssSetNumSFcnParams(S, 0);


    /* Set the number of work vectors */
    if (!IS_SIMULATION_TARGET(S)) {
        ssSetNumPWork(S, 0);
        if (!ssSetNumDWork(S, 0)) return;
    } else {
        ssSetNumPWork(S, 1);
        if (!ssSetNumDWork(S, 2)) return;

        /* Configure the dwork 1 (__dtSizeInfo) */
        ssSetDWorkDataType(S, 0, SS_INT32);
        ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_DWORK);
        ssSetDWorkName(S, 0, "dtSizeInfo");
        ssSetDWorkWidth(S, 0, 3);
        ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);

        /* Configure the dwork 2 (__dtBusInfo) */
        ssSetDWorkDataType(S, 1, SS_INT32);
        ssSetDWorkUsageType(S, 1, SS_DWORK_USED_AS_DWORK);
        ssSetDWorkName(S, 1, "dtBusInfo");
        ssSetDWorkWidth(S, 1, 28);
        ssSetDWorkComplexSignal(S, 1, COMPLEX_NO);
    } /* if */

    /* Set the number of input ports */
    if (!ssSetNumInputPorts(S, 0)) return;

    /* Set the number of output ports */
    if (!ssSetNumOutputPorts(S, 1)) return;

    /* Configure the output port 1 */
    #if defined(MATLAB_MEX_FILE) 
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
        DTypeId dataTypeIdReg;

        ssRegisterTypeFromNamedObject(S, "PosCtrlHandle_t", &dataTypeIdReg);
        if(dataTypeIdReg == INVALID_DTYPE_ID) return;

        ssSetOutputPortDataType(S, 0, dataTypeIdReg);
    } /* if */
    #endif
    ssSetBusOutputObjectName(S, 0, (void *)"PosCtrlHandle_t");
    ssSetBusOutputAsStruct(S, 0, 1);
    {
        int_T y1Width = 1;
        ssSetOutputPortWidth(S, 0, y1Width);
    }
    ssSetOutputPortComplexSignal(S, 0, COMPLEX_NO);
    ssSetOutputPortOptimOpts(S, 0, SS_REUSABLE_AND_LOCAL);
    ssSetOutputPortOutputExprInRTW(S, 0, 0);

    /* Register reserved identifiers to avoid name conflict */
    if (ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) {

        /* Register reserved identifier for  */
        ssRegMdlInfo(S, "PosCtrlInit", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

        /* Register reserved identifier for wrappers */
        if (isSimulationTarget) {

            /* Register reserved identifier for  */
            ssRegMdlInfo(S, "PosCtrlInit_wrapper_Output", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

            /* Register reserved identifier for allocating PWork for SimulationTarget */
            ssRegMdlInfo(S, "sfun_PosCtrlInit_wrapper_allocmem", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

            /* Register reserved identifier for freeing PWork for SimulationTarget */
            ssRegMdlInfo(S, "sfun_PosCtrlInit_wrapper_freemem", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));
        } /* if */
    } /* if */

    /* This S-function can be used in referenced model simulating in normal mode */
    ssSetModelReferenceNormalModeSupport(S, MDL_START_AND_MDL_PROCESS_PARAMS_OK);

    /* Set the number of sample time */
    ssSetNumSampleTimes(S, 1);

    /* Set the compliance for the operating point save/restore. */
    ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);

    ssSetArrayLayoutForCodeGen(S, SS_ALL);

    /* Set the Simulink version this S-Function has been generated in */
    ssSetSimulinkVersionGeneratedIn(S, "10.4");

    /**
     * All options have the form SS_OPTION_<name> and are documented in
     * matlabroot/simulink/include/simstruc.h. The options should be
     * bitwise or'd together as in
     *    ssSetOptions(S, (SS_OPTION_name1 | SS_OPTION_name2))
     */
    ssSetOptions(S,
        SS_OPTION_USE_TLC_WITH_ACCELERATOR |
        SS_OPTION_CAN_BE_CALLED_CONDITIONALLY |
        SS_OPTION_EXCEPTION_FREE_CODE |
        SS_OPTION_WORKS_WITH_CODE_REUSE |
        SS_OPTION_SFUNCTION_INLINED_FOR_RTW |
        SS_OPTION_DISALLOW_CONSTANT_SAMPLE_TIME
    );

    /* Verify Data Type consistency with specification */
    #if defined(MATLAB_MEX_FILE)
    if ((ssGetSimMode(S)!=SS_SIMMODE_SIZES_CALL_ONLY)) {
        CheckDataTypes(S);
    } /* if */
    #endif
}

/* Function: mdlInitializeSampleTimes =====================================
 * Abstract:
 *   This function is used to specify the sample time(s) for your
 *   S-function. You must register the same number of sample times as
 *   specified in ssSetNumSampleTimes.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, INHERITED_SAMPLE_TIME);
    ssSetOffsetTime(S, 0, FIXED_IN_MINOR_STEP_OFFSET);

    #if defined(ssSetModelReferenceSampleTimeDefaultInheritance)
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    #endif
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)
/* Function: mdlSetWorkWidths =============================================
 * Abstract:
 *   The optional method, mdlSetWorkWidths is called after input port
 *   width, output port width, and sample times of the S-function have
 *   been determined to set any state and work vector sizes which are
 *   a function of the input, output, and/or sample times. 
 *   Run-time parameters are registered in this method using methods 
 *   ssSetNumRunTimeParams, ssSetRunTimeParamInfo, and related methods.
 */
static void mdlSetWorkWidths(SimStruct *S)
{
}
#endif

#define MDL_START
#if defined(MDL_START)
/* Function: mdlStart =====================================================
 * Abstract:
 *   This function is called once at start of model execution. If you
 *   have states that should be initialized once, this is the place
 *   to do it.
 */
static void mdlStart(SimStruct *S)
{
    if (IS_SIMULATION_TARGET(S)) {

        /* Access bus/struct information */
        int32_T* __dtSizeInfo = (int32_T*) ssGetDWork(S, 0);
        int32_T* __dtBusInfo = (int32_T*) ssGetDWork(S, 1);


        /* Get common data type Id */
        DTypeId __PosCtrlHandle_tId = ssGetDataTypeId(S, "PosCtrlHandle_t");
        DTypeId __singleId = ssGetDataTypeId(S, "single");
        DTypeId __uint8Id = ssGetDataTypeId(S, "uint8");

        /* Get common data type size */
        __dtSizeInfo[0] = ssGetDataTypeSize(S, __PosCtrlHandle_tId);
        __dtSizeInfo[1] = ssGetDataTypeSize(S, __singleId);
        __dtSizeInfo[2] = ssGetDataTypeSize(S, __uint8Id);

        /* Get information for accessing PosCtrlHandle_t.start_angle */
        __dtBusInfo[0] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 0);
        __dtBusInfo[1] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.angle_step */
        __dtBusInfo[2] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 1);
        __dtBusInfo[3] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.final_angle */
        __dtBusInfo[4] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 2);
        __dtBusInfo[5] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.move_duration */
        __dtBusInfo[6] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 3);
        __dtBusInfo[7] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.sub_step */
        __dtBusInfo[8] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 4);
        __dtBusInfo[9] = 7*__dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.sub_step_duration */
        __dtBusInfo[10] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 5);
        __dtBusInfo[11] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.elapse_time */
        __dtBusInfo[12] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 6);
        __dtBusInfo[13] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.sample_time */
        __dtBusInfo[14] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 7);
        __dtBusInfo[15] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.jerk */
        __dtBusInfo[16] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 8);
        __dtBusInfo[17] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.cruise_spd */
        __dtBusInfo[18] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 9);
        __dtBusInfo[19] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.acceleration */
        __dtBusInfo[20] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 10);
        __dtBusInfo[21] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.omega */
        __dtBusInfo[22] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 11);
        __dtBusInfo[23] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.theta */
        __dtBusInfo[24] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 12);
        __dtBusInfo[25] = __dtSizeInfo[1];

        /* Get information for accessing PosCtrlHandle_t.tc_sts */
        __dtBusInfo[26] = ssGetBusElementOffset(S, __PosCtrlHandle_tId, 13);
        __dtBusInfo[27] = __dtSizeInfo[2];


        /* Alloc memory for the pwork 1 (__y1BUS) */
        {
            PosCtrlHandle_t* __y1BUS = (PosCtrlHandle_t*)calloc(sizeof(PosCtrlHandle_t), ssGetOutputPortWidth(S, 0));
            if (__y1BUS==NULL) {
                ssSetErrorStatus(S, "Unexpected error during the memory allocation for __y1BUS");
                return;
            } /* if */
            ssSetPWorkValue(S, 0, __y1BUS);
        }

    } /* if */
}
#endif

/* Function: mdlOutputs ===================================================
 * Abstract:
 *   In this function, you compute the outputs of your S-function
 *   block. Generally outputs are placed in the output vector(s),
 *   ssGetOutputPortSignal.
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
    if (IS_SIMULATION_TARGET(S)) {

        /* Access bus/struct information */
        int32_T* __dtSizeInfo = (int32_T*) ssGetDWork(S, 0);
        int32_T* __dtBusInfo = (int32_T*) ssGetDWork(S, 1);


        /* Get access to Parameter/Input/Output/DWork data */
        char* y1 = (char*) ssGetOutputPortSignal(S, 0);

        PosCtrlHandle_t* __y1BUS = (PosCtrlHandle_t*) ssGetPWorkValue(S, 0);

        /* Call the legacy code function */
        PosCtrlInit(__y1BUS);

        /* Assign the user structure __y1BUS to the Simulink structure y1 */
        (void) memcpy(y1 +  __dtBusInfo[0], &__y1BUS[0].start_angle,  __dtBusInfo[1]);
        (void) memcpy(y1 +  __dtBusInfo[2], &__y1BUS[0].angle_step,  __dtBusInfo[3]);
        (void) memcpy(y1 +  __dtBusInfo[4], &__y1BUS[0].final_angle,  __dtBusInfo[5]);
        (void) memcpy(y1 +  __dtBusInfo[6], &__y1BUS[0].move_duration,  __dtBusInfo[7]);
        (void) memcpy(y1 +  __dtBusInfo[8], __y1BUS[0].sub_step,  __dtBusInfo[9]);
        (void) memcpy(y1 +  __dtBusInfo[10], &__y1BUS[0].sub_step_duration,  __dtBusInfo[11]);
        (void) memcpy(y1 +  __dtBusInfo[12], &__y1BUS[0].elapse_time,  __dtBusInfo[13]);
        (void) memcpy(y1 +  __dtBusInfo[14], &__y1BUS[0].sample_time,  __dtBusInfo[15]);
        (void) memcpy(y1 +  __dtBusInfo[16], &__y1BUS[0].jerk,  __dtBusInfo[17]);
        (void) memcpy(y1 +  __dtBusInfo[18], &__y1BUS[0].cruise_spd,  __dtBusInfo[19]);
        (void) memcpy(y1 +  __dtBusInfo[20], &__y1BUS[0].acceleration,  __dtBusInfo[21]);
        (void) memcpy(y1 +  __dtBusInfo[22], &__y1BUS[0].omega,  __dtBusInfo[23]);
        (void) memcpy(y1 +  __dtBusInfo[24], &__y1BUS[0].theta,  __dtBusInfo[25]);
        (void) memcpy(y1 +  __dtBusInfo[26], &__y1BUS[0].tc_sts,  __dtBusInfo[27]);
    } /* if */
}

/* Function: mdlTerminate =================================================
 * Abstract:
 *   In this function, you should perform any actions that are necessary
 *   at the termination of a simulation.
 */
static void mdlTerminate(SimStruct *S)
{
    if (IS_SIMULATION_TARGET(S)) {

        /* Access bus/struct information */
        int32_T* __dtSizeInfo = (int32_T*) ssGetDWork(S, 0);
        int32_T* __dtBusInfo = (int32_T*) ssGetDWork(S, 1);


        /* Free memory for the pwork 1 (__y1BUS) */
        {
            PosCtrlHandle_t* __y1BUS = (PosCtrlHandle_t*)ssGetPWorkValue(S, 0);
            if (__y1BUS!=NULL) {
                free(__y1BUS);
                ssSetPWorkValue(S, 0, NULL);
            } /* if */
        }

    } /* if */
}

/* Function: CheckDataTypeChecksum ========================================
 * Abstract:
 *   CheckDataTypeChecksum invokes a MATLAB helper for checking the consistency
 *   between the data type definition used when this S-Function was generated
 *   and the data type used when calling the S-Function.
 */
static int_T CheckDataTypeChecksum(SimStruct *S, const char* dtypeName, uint32_T* chkRef)
{
    mxArray *plhs[1] = {NULL};
    mxArray *prhs[3];
    mxArray *err = NULL;
    const char *bpath = ssGetPath(S);
    int_T status = -1;

    prhs[0] = mxCreateString(bpath);
    prhs[1] = mxCreateString(dtypeName);
    prhs[2] = mxCreateDoubleMatrix(1, 4, mxREAL);
    mxGetPr(prhs[2])[0] = chkRef[0];
    mxGetPr(prhs[2])[1] = chkRef[1];
    mxGetPr(prhs[2])[2] = chkRef[2];
    mxGetPr(prhs[2])[3] = chkRef[3];

    err = mexCallMATLABWithTrap(1, plhs, 3, prhs, "legacycode.LCT.getOrCompareDataTypeChecksum");
    mxDestroyArray(prhs[0]);
    mxDestroyArray(prhs[1]);
    mxDestroyArray(prhs[2]);

    if (err==NULL && plhs[0]!=NULL) {
        status = mxIsEmpty(plhs[0]) ? -1 : (int_T) (mxGetScalar(plhs[0]) != 0);
        mxDestroyArray(plhs[0]);
    } /* if */

    return status;
}

/* Function: CheckDataTypes ===============================================
 * Abstract:
 *   CheckDataTypes verifies data type consistency between the data type 
 *   definition used when this S-Function was generated and the data type
 *   used when calling the S-Function.
 */
static void CheckDataTypes(SimStruct *S)
{

    /* Verify Bus/StructType 'PosCtrlHandle_t', specification */
    {
        uint32_T chk[] = {2660361461, 2037022453, 1549278055, 4195284205};
        int_T status;
        status = CheckDataTypeChecksum(S, "PosCtrlHandle_t", &chk[0]);
        if (status==-1) {
          ssSetErrorStatus(S, "Unexpected error when checking the validity of the Simulink Bus/StructType 'PosCtrlHandle_t'");
        } else if (status==0) {
          ssSetErrorStatus(S, "The Simulink Bus/StructType 'PosCtrlHandle_t' definition has changed since the S-Function was generated");
        }
    }
}

/* Function: GetRTWEnvironmentMode ========================================
 * Abstract:
 *   Must be called when ssRTWGenIsCodeGen(S)==true. This function
 *   returns the code generation mode:
 *       -1 if an error occurred
 *        0 for standalone code generation target
 *        1 for simulation target (Accelerator, RTW-SFcn,...)
 */
static int_T GetRTWEnvironmentMode(SimStruct *S)
{
    int_T status;
    mxArray * err;
    mxArray *plhs[1];
    mxArray *prhs[1];

    /* Get the name of the Simulink block diagram */
    prhs[0] = mxCreateString(ssGetModelName(ssGetRootSS(S)));
    plhs[0] = NULL;

    /* Call "isSimulationTarget = rtwenvironmentmode(modelName)" in MATLAB */
    err = mexCallMATLABWithTrap(1, plhs, 1, prhs, "rtwenvironmentmode");

    mxDestroyArray(prhs[0]);

    /* Set the error status if an error occurred */
    if (err) {
        if (plhs[0]) {
            mxDestroyArray(plhs[0]);
            plhs[0] = NULL;
        } /* if: } */
        ssSetErrorStatus(S, "Unknown error during call to 'rtwenvironmentmode'.");
        return -1;
    } /* if */

    /* Get the value returned by rtwenvironmentmode(modelName) */
    if (plhs[0]) {
        status = (int_T) (mxGetScalar(plhs[0]) != 0);
        mxDestroyArray(plhs[0]);
        plhs[0] = NULL;
    } /* if */

    return status;
}

/* Required S-function trailer */
#ifdef    MATLAB_MEX_FILE
# include "simulink.c"
#else
# include "cg_sfun.h"
#endif

