#ifndef ADC_CONFIG_H
#define ADC_CONFIG_H

#include "Board_Adc.h"
#include "adc.h"
#include "stm32f4xx_hal_adc.h"

/* 已配置的逻辑通道数量，供 Board_Adc.c 做静态计数校验 */
#define ADC_CONFIGURED_CHANNEL_COUNT ADC_CH_ID_COUNT

/* 单个 ADC 实例的规则通道最大 rank 数，决定 DMA 缓冲区深度 */
#define ADC_REGULAR_RANK_MAX (2U)

/* 单个 ADC 实例的注入通道最大 rank 数，决定注入结果快照深度 */
#define ADC_INJECTED_RANK_MAX (4U)

/* 注入组硬件触发源：TIM1_CH4 上升沿，与 PWM 载波同步 */
#define ADC_INJECTED_TRIGGER_SOURCE ADC_EXTERNALTRIGINJECCONV_T1_CC4
#define ADC_INJECTED_TRIGGER_EDGE   ADC_EXTERNALTRIGINJECCONVEDGE_RISING

/* U 相电流：ADC2 注入通道 IN8，注入 rank 3 */
#define ADC_CH_PHASE_U_CURRENT_INSTANCE      ADC_INSTANCE_2
#define ADC_CH_PHASE_U_CURRENT_HW_CHANNEL    ADC_CHANNEL_8
#define ADC_CH_PHASE_U_CURRENT_SAMPLING_TIME ADC_SAMPLETIME_15CYCLES
#define ADC_CH_PHASE_U_CURRENT_RANK          (3U)
#define ADC_CH_PHASE_U_CURRENT_KIND          ADC_CH_KIND_INJECTED
#define ADC_CH_PHASE_U_CURRENT_ENABLED       (1U)

/* V 相电流：ADC2 注入通道 IN6，注入 rank 2 */
#define ADC_CH_PHASE_V_CURRENT_INSTANCE      ADC_INSTANCE_2
#define ADC_CH_PHASE_V_CURRENT_HW_CHANNEL    ADC_CHANNEL_6
#define ADC_CH_PHASE_V_CURRENT_SAMPLING_TIME ADC_SAMPLETIME_15CYCLES
#define ADC_CH_PHASE_V_CURRENT_RANK          (2U)
#define ADC_CH_PHASE_V_CURRENT_KIND          ADC_CH_KIND_INJECTED
#define ADC_CH_PHASE_V_CURRENT_ENABLED       (1U)

/* W 相电流：ADC2 注入通道 IN3，注入 rank 1 */
#define ADC_CH_PHASE_W_CURRENT_INSTANCE      ADC_INSTANCE_2
#define ADC_CH_PHASE_W_CURRENT_HW_CHANNEL    ADC_CHANNEL_3
#define ADC_CH_PHASE_W_CURRENT_SAMPLING_TIME ADC_SAMPLETIME_15CYCLES
#define ADC_CH_PHASE_W_CURRENT_RANK          (1U)
#define ADC_CH_PHASE_W_CURRENT_KIND          ADC_CH_KIND_INJECTED
#define ADC_CH_PHASE_W_CURRENT_ENABLED       (1U)

/* 母线电压：ADC1 规则通道 IN9，规则 rank 2 */
#define ADC_CH_DC_BUS_VOLTAGE_INSTANCE      ADC_INSTANCE_1
#define ADC_CH_DC_BUS_VOLTAGE_HW_CHANNEL    ADC_CHANNEL_9
#define ADC_CH_DC_BUS_VOLTAGE_SAMPLING_TIME ADC_SAMPLETIME_15CYCLES
#define ADC_CH_DC_BUS_VOLTAGE_RANK          (2U)
#define ADC_CH_DC_BUS_VOLTAGE_KIND          ADC_CH_KIND_REGULAR
#define ADC_CH_DC_BUS_VOLTAGE_ENABLED       (1U)

/* 功率级温度：ADC1 规则通道 IN0，规则 rank 1 */
#define ADC_CH_POWER_STAGE_TEMP_INSTANCE      ADC_INSTANCE_1
#define ADC_CH_POWER_STAGE_TEMP_HW_CHANNEL    ADC_CHANNEL_0
#define ADC_CH_POWER_STAGE_TEMP_SAMPLING_TIME ADC_SAMPLETIME_15CYCLES
#define ADC_CH_POWER_STAGE_TEMP_RANK          (1U)
#define ADC_CH_POWER_STAGE_TEMP_KIND          ADC_CH_KIND_REGULAR
#define ADC_CH_POWER_STAGE_TEMP_ENABLED       (1U)

#endif /* ADC_CONFIG_H */
